### ISSUE TITLE
Which version of tensorflow is needed

### ISSUE THREAD

**Issue by Jallet** [geek-ai/irgan#7]
I encountered a error while trying to run the experiments of Question-Answering, I doubt it is the version of tensorflow that cause this error. Could you please tell me which version of tensorflow do you use. If tensorflow version is not the reason, could you please give me some advice on fixing this error. Thank!
Following is the Trace Back of this error:
Traceback (most recent call last):
  File "baseline.py", line 226, in <module>
    main()
  File "baseline.py", line 197, in main
    loss="pair")
  File "/gruntdata/public/tianxuan.jl/code/irgan/Question-Answer/Discriminator.py", line 12, in __init__
    QACNN.__init__(self, sequence_length, batch_size,vocab_size, embedding_size,filter_sizes, num_filters, dropout_keep_prob=dropout_keep_prob,l2_reg_lambda=l2_reg_lambda,paras=paras,learning_rate=learning_rate,embeddings=embeddings,loss=loss,trainable=trainable)
  File "/gruntdata/public/tianxuan.jl/code/irgan/Question-Answer/QACNN.py", line 70, in __init__
    q  =self.getRepresentation(self.input_x_1)
  File "/gruntdata/public/tianxuan.jl/code/irgan/Question-Answer/QACNN.py", line 101, in getRepresentation
    pooled_reshape = tf.reshape(tf.concat(3, output), [-1, self.num_filters_total]) 
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by Leavingseason** [comment]
FYI, my tensorflow version is 1.0.0, and not issue with tf version.
Since my python is 3.5, I need to adapt some initial code (written in python 2) to python 3 then I can run the code.

**Comment by wabyking** [comment]
Thank Leavingseason and Jallet !
I test the code in TensorFlow 0.12, it works.  
Sorry for that it does not support the newest version.
It may cost a little time to transfer it to the newest Tensorflow. I may update it if not busy. But I cannot confirm the time schedule.
Benyou
